version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: speedometer

    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build: ./backend
    depends_on:
      mysql:
        condition: service_healthy
    command: uvicorn main:app --reload
    environment:
      DATABASE_URL: mysql://root:password@mysql_db:3306/speedometer
    ports:
      - "8000:8000"

  react:
    image: node:14
    command: sh -c "cd /app && npm install && npm start"
    volumes:
      - ./react-app:/app
    ports:
      - "3000:3000"
  
  # backend:
  #   image: backend
  #   command: uvicorn main:app --reload

  speedometer-frontend:
    image: speedometer-frontend
